services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cdn-nginx
    expose:
      - "80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - traefik-network
      - cdn-internal

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cdn-api
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - ./static:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - traefik-network
      - cdn-internal
    depends_on:
      - nginx
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: cdn-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cdn-internal

  redis:
    image: redis:alpine
    container_name: cdn-redis
    restart: unless-stopped
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cdn-internal

  prometheus:
    image: prom/prometheus:latest
    container_name: cdn-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - cdn-internal

  grafana:
    image: grafana/grafana:latest
    container_name: cdn-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - prometheus
    networks:
      - cdn-internal
      - traefik-network

networks:
  traefik-network:
    external: true
  cdn-internal:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
